version: '3.8'

services:
  postgres:
    image: postgres:18-alpine
    container_name: backstage-postgres
    restart: always
    environment:
      POSTGRES_USER: backstage_db_user
      POSTGRES_PASSWORD: backstage_db_password
      POSTGRES_DB: backstage_db
    ports:
      - '5432:5432'
    volumes:
      # Maps the local folder "./postgres_data" to the Postgres internal data directory
      - ./postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U backstage_db_user -d backstage_db']
      interval: 10s
      timeout: 5s
      retries: 5
